### ISSUE TITLE
Unable to add richCombo using editor.ui.addRichCombo()

### ISSUE THREAD

**Issue by jpmrcado** [ckeditor/ckeditor4-angular#101]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

Please see sample here (with workaround I'm currently using)
https://stackblitz.com/edit/github-emmt7u?file=src%2Fapp%2Fsimple-usage%2Fsimple-usage.component.ts

I'm not sure if this really is a bug or I'm doing something incorrectly with my integration. I used the top editor's ready event to attempt to add a richcombo but is not rendering.

The bottom editor used a modified ckeditor component to emit the `instanceCreated` event which I then used to call `editor.ui.addRichCombo()` to work around the issue

### Expected result

On load, calling `editor.ui.addRichCombo()` should display a richcombo in the editor.

### Actual result

On load, calling `editor.ui.addRichCombo()` does not display a richcombo in the editor.

## Other details

* Browser: Chrome 81.0.4044.129 
* OS: Windows 10
* Integration version: current included in this repo
* CKEditor version: current included in this repo
* Installed CKEditor plugins: current included in this repo

**Comment by f1ames** [comment]
Hello @jpmrcado,

The [`onReady` event](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-instanceReady) is a little too late to add stuff to the toolbar since it is already rendered and new entities would not be added - so this work as intended.

Your workaround makes sense, however, in most cases adding stuff to toolbar is done by plugins which has it's own lifecycle (see [docs](https://ckeditor.com/docs/ckeditor4/latest/guide/plugin_sdk_intro.html)), so that would be the proper solution here. You may also try [customizing component config](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#config) and [`config.on`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-on) to attach listeners, but that will be another workaround.

Since your custom change adds another place to hook into component lifecycle, feel free to wrap it in the PR so we can add it to the integration :+1:

**Comment by jpmrcado** [comment]
I decided to go with the plugin approach to fix my issue.

Looks like my work around might cause unwanted behavior when used with multiple ckeditor instances since the event I used was part of `CKEDITOR` instead of `CKEDITOR.editor` so I'll just leave it at that.

Thank you!
