### ISSUE TITLE
how to add keyup and keydown events to ckeditor tag

### ISSUE THREAD

**Issue by rajathammineni** [ckeditor/ckeditor4-angular#137]
## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
