### ISSUE TITLE
How to integrate wordcount plugin in ckeditor4-angular?

### ISSUE THREAD

**Issue by rishabh47** [ckeditor/ckeditor4-angular#139]

**Comment by f1ames** [comment]
Please refer to [CKEditor 4 Angular integration documentation](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#config).

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) next time, where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
