### ISSUE TITLE
autocomplete plugin is not working in ckeditor4-angular

### ISSUE THREAD

**Issue by sedhurabe** [ckeditor/ckeditor4-angular#156]
## Type of report

I am using this ckeditor4 in my angular project. I had install ckeditor4-angular package in my application. In my editor, I tried to add the autocomplete with this reference link https://ckeditor.com/docs/ckeditor4/latest/examples/autocomplete.html. but it not working for me

* StackBlitz: https://stackblitz.com/edit/ckeditor-autocomplete?file=src/app/app.component.ts

### Expected result

https://ckeditor.com/docs/ckeditor4/latest/examples/autocomplete.html

### Actual result

autocomplete is not rendering if check this link for my code https://stackblitz.com/edit/ckeditor-autocomplete?file=src/app/app.component.ts

## Other details

* Browser: Chrome,firebox
* OS: window
* CKEditor version: 14.15.1
* Installed CKEditor plugins: ckeditor4-angular

**Comment by Dumluregn** [comment]
Hello,
unfortunately your sample doesn't work not only in terms of autocomplete, but the custom config you try to apply doesn't work at all (you can see that your editor should have only `autocomplete` and `textmatch` plugins, but it uses a standard build instead).

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Since this is most probably implementation issue, I'm closing it - please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. If you have CKEditor license, please contact our support team.

**Comment by arunvc** [comment]
Working sample ckeditor4-angular

https://stackblitz.com/edit/ckeditor-autocomplete-16drbw?file=src%2Fapp%2Fapp.component.ts
