### ISSUE TITLE
CKEDITOR inline

### ISSUE THREAD

**Issue by isuruhera** [ckeditor/ckeditor4-angular#174]
how to create ckeditor inline by code ?
like https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html#

**Comment by sculpt0r** [comment]
Hi @isuruhera ,

Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).  
  
However, please take a look at https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#choosing-the-editor-type
