### ISSUE TITLE
Template js doesn't work after CKEditor enable/disable.

### ISSUE THREAD

**Issue by armang98** [ckeditor/ckeditor4-angular#219]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
In my template I was integrate editor, and I have logic that user can enable/disable editor, after disable editor template's tab navigation doesn't work.
Video: 
https://user-images.githubusercontent.com/37144283/133139868-445a64af-b5c1-4cdd-b82a-bab2dd1c8d2d.mp4

Description of video:
At the start editor is enabled (places where there are dashed lines these are editable areas, and editor can work), and I do not click any area and just disable editor, after that I click on tabs and they works, but after I again enable editor, click on of tabs, editor starts working, and again I do not change anything, just activate editor on this tab area, and after again disable editor and after that when I click on tabs they do not work, it's strange because in Inspect element I see that nothing changed in html part also (e.g. deleting any attribute or something like this). 

P.S. If I do click on other area (not on tab) editors activate and after that disable editor, tabs works perfectly, I'm getting this issue only in case when I do click on tab navigation area.

### Expected result

*Expecting that editor will not affect in template js file.*

## Other details

* Browser: Google Chrome
* OS: Windows 10
* CKEditor version: ^4.15.0
* Installed CKEditor plugins: Standards.

**Comment by MMMalik** [comment]
Hello @armang98,

Thank you for your effort in providing the sample. The first thing I noticed is that you are not using our official `ckeditor4-angular` [integration](https://github.com/ckeditor/ckeditor4-angular). My suggestion is that you give it a try.

Moreover, the issues you are experiencing are most likely not related to CKEditor 4 and are quite possibly related to the way you manage state of your tabs.

This being said, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on Stack Overflow where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at Stack Overflow.

**Comment by armang98** [comment]
Hi @MMMalik , I have published my question on Stack Overflow and I hope your team will help me to get solution of this, and I'm almost sure that it's editor's bug because I have tried many way to manage state of my tabs(pure js, jquery, other tab navigation libs.. ) and no one way works in this case. 
**Stack Overflow link:** https://stackoverflow.com/questions/69426746/template-js-doesnt-work-after-ckeditor-enable-disable
