### ISSUE TITLE
Page break plugin

### ISSUE THREAD

**Issue by prashantkushwaha003** [ckeditor/ckeditor4-angular#226]
Hi, There is no page break plugin, if possible can you provide in next release ?

**Comment by Comandeer** [comment]
You can [customize the editor](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#config) that is provided with the Angular integration and add the Page Break plugin:

```tsx
<ckeditor
    data="<p>Editor' content</p>"
    [config]="{ extraPlugins: 'pagebreak' }"
></ckeditor>
```

Please also note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
