### ISSUE TITLE
Currenlty there is no way to open dialog box from a custom added button in the toolbar

### ISSUE THREAD

**Issue by parascodejudge** [ckeditor/ckeditor4-angular#235]
So the CKeditor api provides api to add definition of a dialog for the editor and then you can open that dialog box from exec function of add command of the button. How can i open a dialog box after clicking on the custom button
CKEDITOR.dialog.add

**Comment by sculpt0r** [comment]
Hi @parascodejudge 
 There is an option in the dialog API: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-openDialog
 
 Please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, therefore please leave your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/ckeditor) where our team and the community assist other users in solving their issues. Also, since CKEditor is an Open Source software, we believe it’s crucial to share proposed solutions and make others benefit from them.

If you have CKEditor license, please contact our support team. You also can ask your implementation questions at [ Stack Overflow](http://stackoverflow.com/questions/tagged/ckeditor).
