### ISSUE TITLE
Ivy compiler for Angular v13 and later

### ISSUE THREAD

**Issue by EduardoCastanho** [ckeditor/ckeditor4-angular#242]
Hi !

Has expected with angular 16 :

> Error: src/app/app.module.ts:207:5 - error NG6002: 'CKEditorModule' does not appear to be an NgModule class.
> 
> 207     CKEditorModule,
>         ~~~~~~~~~~~~~~
> 
>   node_modules/ckeditor4-angular/ckeditor.module.d.ts:5:22
>     5 export declare class CKEditorModule {
>                            ~~~~~~~~~~~~~~
>     This likely means that the library (ckeditor4-angular) which declares CKEditorModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> 
> 
Any solution ?  workaround?

cheers

**Comment by KarolDawidziuk** [comment]
Hi @EduardoCastanho

We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor4-angular/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. In this case, it is very difficult to see where the problem lies and a working example would be very helpful. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

**Comment by KernelFolla** [comment]
I'm stuck too so please reopen this, you would still have other identical reports:)

There's not much to explain to reproduce, it just doesn't work in angular 16 because it's not compiled with Ivy and ngcc support is removed so actually ckeditor4-angular doesn't support angular 16

**Comment by EduardoCastanho** [comment]
> Hi @EduardoCastanho
> 
> We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor4-angular/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. In this case, it is very difficult to see where the problem lies and a working example would be very helpful. Without this, we are unable to have a closer look at your problem.
> 
> Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

I don't miss the template!  using a template for a simple and obvious thing .... only noise .

With this reply and closing the issue, without  even tackle the issue  It seems that there is no will to solve this problem, at least in a near future ...

 [https://github.com/ckeditor/ckeditor5-angular](https://github.com/ckeditor/ckeditor5-angular)

May be ?

**Comment by KarolDawidziuk** [comment]
@EduardoCastanho, Using the template is useful to check the reported issue from our side because it contains useful information for us to confirm it on not. In addition, the information may be useful to other community members.

I am re-opening this issue.
