### ISSUE TITLE
Check backwards compatibility with older Angular version

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-angular#39]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

Since we developed the integration with latest Angular version, it's not clear which older versions are supported. The assumption was it should be Angular 2+, however it was never checked.

The compatibility with older versions should be checked and short section added to readme file (could be similar to what CKE5 have - https://github.com/ckeditor/ckeditor5-angular#supported-angular-versions).

**Comment by engineering-this** [comment]
## Angular 6+
Works fine.

## Angular 5

Throws an error, it can be fixed by changing 
https://github.com/ckeditor/ckeditor4-angular/blob/32f1249ac52edde25c9f4c2020213fdefaca784f/src/ckeditor/ckeditor.component.ts#L194

to
```
constructor( private elementRef: ElementRef, private ngZone: NgZone ) { 
```

Reason is that `elementRef` isn't a [generic type](https://www.tutorialsteacher.com/typescript/typescript-generic-class) before Angular 6. However this change doesn't seem to break anything in newer versions. I'll provide PR.

## Angular 4

Angular 4 has incompatible package meta-data format, so it won't work without separate package.
