### ISSUE TITLE
ckeditor4 elementRef line number 113  is not generic in angular

### ISSUE THREAD

**Issue by sanmscse** [ckeditor/ckeditor4-angular#42]
ckeditor4 elementRef line number 113  is not generic in angular

**Comment by ma2ciek** [comment]
The `ElementRef` is generic - see https://angular.io/api/core/ElementRef.

And I don't know which line you talk about and what's the real issue.

**Comment by sanmscse** [comment]
![image](https://user-images.githubusercontent.com/40461278/61935225-aee2a900-afa7-11e9-8a08-29e77f27fc48.png)
When build angular code
using "npm start"

command window throw error on this line 
i've installed ckeditor using 
npm i ckeditor4-angular

**Comment by sanmscse** [comment]
Hi @ma2ciek 

can we display file blob in ckEditor 
my file is a Word document i've read it from another API and have to display in ckEditor
bloburl = "blob:http://localhost:49842/d673f9dd-5653-413b-b5ff-429cf21191bf"

Can you help me to display this in ckEditor data

<ckeditor [(ngModel)]="mycontent"
                          #myckeditor="ngModel"
                          name="myckeditor"
                          required
                          [config]="ckeConfig"
                          debounce="500"
                          >
                </ckeditor>

**Comment by ma2ciek** [comment]
Since you've installed the `ckeditor4-angular` you don't need to touch any source code. And the issue is that you use an old version of Angular, that's probably why the error shows up.

I'm not a specialist in the CKEditor 4 ecosystem, so I won't help you here. And AFAIK we don't provide any Word file loader, but I might be wrong.

**Comment by f1ames** [comment]
Thanks @ma2ciek for checking this issue, it's related to #39.

@sanmscse at the moment Angular 6+ is supported. After #40 will be closed also Angular 5 will be supported and this issue should be solved, since [it concerns the generic type you mentioned](https://github.com/ckeditor/ckeditor4-angular/pull/40/files#diff-756e5674b9c69ad85fad09a2b0c3e852L194).

**Comment by sanmscse** [comment]
Hi @f1ames , @ma2ciek  , @Reinmar  , @jodator 

Can we load the blob or byte array (which might be .docx/.pdf) 
can we load the content in ckEditor 

i've tried in config.BaseHref =  "blob:http://localhost:49842/d673f9dd-5653-413b-b5ff-429cf21191bf"

but not works. Can you suggest some ideas on this

Thanks

**Comment by f1ames** [comment]
@sanmscse your last https://github.com/ckeditor/ckeditor4-angular/issues/42#issuecomment-515394626 is not related to Angular integration. If you have any issues or feature requests regarding CKEditor 4 you may report in [ckeditor-dev repository](https://github.com/ckeditor/ckeditor-dev).

As for handling blobs, CKEditor don't support it. You may use external code which will convert blob to HTML and then feed such data to CKEditor.
