### ISSUE TITLE
Clicking on save button, refresh entire page

### ISSUE THREAD

**Issue by brucebrit** [ckeditor/ckeditor4-angular#84]
Hi, 
Problem: When i click on the save button, it keeps refreshing the entire page.
Question:  I manage to capture the click event of the ckeditor4 buttons using the (click). But i can't prevent it from refreshing the entire page, despite me returning false in the click event handler function. 
Another Question: How do i check if the ckeditor4  button i have clicked is the save button?

**Comment by jacekbogdanski** [comment]
[Save](https://ckeditor.com/cke4/addon/save) plugin just submits underlying editor form to the server using native browser mechanism, you can see the implementation here:

https://github.com/ckeditor/ckeditor4/blob/01b82d9d86eb1ebabf68934dcf71823f12bf7db8/plugins/save/plugin.js#L15-L31

For SPA apps built with frameworks like Angular, it doesn't really work as we don't want to refresh whole page in most cases. So overall, you end up with a custom implementation where you intercept `save` command and calling own API:

```javascript
editor.on( 'beforeCommandExec', function( evt ) {
  var commandName = evt.data.command.name;
  if ( commandName === 'save' ) {
    // Do some stuff with editor data.
    callAPI( editor.getData() );
  }
  // Prevent `save` command to be called.
  return false;
}
```

or requesting a new feature giving more flexibility over Save plugin like defining your own callback instead of form submission at https://github.com/ckeditor/ckeditor4/issues
